# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40ab42d9149fffa5274b0de78ac82b521ff5aac1004a132a8a3e46cfa495a6a7849f496bf17bc7f3a7eb0c97a128d0393e07be5a18f61a8b77edcc6b84f1e322
  smtp_adress: <%= ENV["SMTP_ADRESS"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  domain_name: <%= ENV["EMAIL_DOMAIN"] %>
  smtp_auth: <%= ENV['SMTP_AUTH'] %>
  email_username: <%= ENV["EMAIL_USERNAME"] %>
  email_password: <%= ENV["EMAIL_PASSWORD"] %>
  email_bcc: <%= ENV["EMAIL_BCC"] %>
  smtp_tls: <%= ENV["SMTP_TLS"] %>

test:
  secret_key_base: 8fa591881226e069a53fb6a7cd52a3e791da0a059900c00c0d7b5dedd68043a9d5f83ef4d4657ae6a763f5062ba389480dee4ea4f410a7015828a0059f26db95
  # for e-mail
  smtp_adress: <%= ENV["SMTP_ADRESS"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  domain_name: <%= ENV["EMAIL_DOMAIN"] %>
  smtp_auth: <%= ENV["SMTP_AUTH"] %>
  email_username: <%= ENV["EMAIL_USERNAME"] %>
  email_password: <%= ENV["EMAIL_PASSWORD"] %>
  email_bcc: <%= ENV["EMAIL_BCC"] %>
  smtp_tls: <%= ENV["SMTP_TLS"] %>
  default_url: <%= ENV["TEST_DEFAULT_URL"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # for e-mail
  smtp_adress: <%= ENV["SMTP_ADRESS"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  domain_name: <%= ENV["EMAIL_DOMAIN"] %>
  smtp_auth: <%= ENV["SMTP_AUTH"] %>
  email_username: <%= ENV["EMAIL_USERNAME"] %>
  email_password: <%= ENV["EMAIL_PASSWORD"] %>
  email_bcc: <%= ENV["EMAIL_BCC"] %>
  smtp_tls: <%= ENV["SMTP_TLS"] %>
  default_url: <%= ENV["DEFAULT_URL"] %>
